= Strongly typed filesystem manipulation

Efforts to create strongly-typed code are often poisoned by string file path references spread all over the same codebase.

We constantly see code like this refering to file paths with strings.  This one has to have a typo in it.  Which is correct, `resource` or `resources`?

[source,java]
----
final Path moduleDir = ...
final Path srcMainResources = moduleDir.resolve("src/main/resources");
final Path srcTestResources = moduleDir.resolve("src/test/resource");
----

What if you could have typo-proof, compile-time checked and code-completable paths like this?  Perhaps DSL-style approach to file paths, like so:

----
final Path moduleDir = ...
final Module module = Dir.of(Module.class, moduleDir);
final Path srcMainResources = module.src().main().resources();
final Path srcTestResources = module.src().test().resources();
----

This utility was born out of a desire that all path references could be compile-time checked and code completed.

== Step 1 Create an interface matching a directory

For example, a directory structure like this:

[source]
----
 project/
   - src/
   - target/
   - .git/
   - pom.xml
----

Could be handled with the following interface:

[source,java]
----
 public interface Project {
     Path src();
     Path target();
     @Name(".git")
     Path git();
     @Name("pom.xml")
     Path pomXml();
 }
----

== Step 2 Get a proxied reference to that directory

[source,java]
----
import org.tomitribe.util.paths.Dir;

Path mydir = java.nio.file.Paths.get("/some/path/to/a/project");
Project project = Dir.of(Project.class,  mydir);
----

Under the covers the interface is implemented as a dynamic proxy whose InvocationHandler is
 holding the actual `Path` object.

== Returning Another Interface

Instead of `src()` returning a `Path`, it could return another similar interface. For example

[source,java]
----
 public interface Src {
     Path main();
     Path test();
 }
----

And now we update `Project` so the `src()` method will return `Src`

[source,java]
----
 public interface Project {
     Src src();
     Path target();
     @Name(".git")
     Path git();
     @Name("pom.xml")
     Path pomXml();
 }
----

Now we have a strongly-typed directory structure that also supports code completion in the IDE.

== Passing a Subdirectory Name

There may be times when you don't know the exact subdirectory name, but you know that it will use a specific
 directory structure.  Here's how you might reference a nested Maven module structure:

[source,java]
----
 public interface Module {
     @Name("pom.xml")
     Path pomXml();
     Path src();
     Path target();
     Module submodule(String name);
 }
----


== `@Name` for indicating file names

By default file names are derived from the method name.  The following would indicate a directory or file named `src` under the module directory.

[source,java]
----
public interface Module {

    Path src();
}
----

But what if you had a filename with a dot or other illegal java character for method name?  Just use `@Name` to indicate the expected file name:

[source,java]
----
public interface Module {
    Path src();

    @Name("pom.xml")
    Path pomXml();
}
----

This can also be useful for files that are otherwise hidden, such as `.gitignore`


[source,java]
----
public interface Module {
    Path src();

    @Name("pom.xml")
    Path pomXml();

    @Name(".gitignore")
    Path gitignore();
}
----

== Listing Files

Let's imagine we have a Maven project structure with many submodules.  How do we list the `cheese` and `pepperoni` submodules?

----
pizza/
   pom.xml
   cheese/
      pom.xml
      src/
   pepperoni/
      pom.xml
      src/
   target/
----

=== Array of `Path`

The simplest way is to return an array of `java.nio.file.Path` such as:

[source,java]
----
public interface Project {
    Path[] modules();
}
----

This is close, but we haven't given any way for unwanted directories such as `target` to be filtered out.

=== `@Filter` Array of `Path`

To get just `Path` instances that are directories and contain a `pom.xml` we can create a simple `Predicate<Path>`, like so:

[source,java]
----
import java.nio.file.Path;
import java.util.function.Predicate;

public static class HasPomXml implements Predicate<Path> {
    @Override
    public boolean test(final Path path) {
        return java.nio.file.Files.exists(path.resolve("pom.xml"));
    }
}
----

Then we can use it to filter out anything not accepted by our `HasPomXml` filter

[source,java]
----
import  org.tomitribe.util.paths.Filter;

public interface Project {

    @Filter(HasPomXml.class)
    Path[] modules();
}
----

=== Array of `interface`

Of course, the main goal of the `Dir` utility is to elimnate `Path` references where possible.  So let's put our `Module` interface back like so:

[source,java]
----
public interface Project {

    @Filter(HasPomXml.class)
    Module[] modules();
}
----

[source,java]
----
public interface Module {

    @Name("pom.xml")
    Path pomXml();

    Src src();
}
----

=== `Stream` of an `interface`

Arrays are fine, but often it's far more fun to use `java.util.stream.Stream`

[source,java]
----
import java.util.stream.Stream;

public interface Project {
    @Filter(HasPomXml.class)
    Stream<Module> modules();
}
----

[source,java]
----
public interface Module {

    @Name("pom.xml")
    Path pomXml();

    Src src();
}
----

=== Repeatable `@Filter` annotations

The `@Filter` annotation is repeatable, so you can stack multiple filters on a single method.  All filters must pass for a path to be included.

[source,java]
----
public interface Work extends Dir {
    @Walk
    @Filter(IsJunit.class)
    @Filter(IsTxt.class)
    Stream<Path> junitTxtFiles();
}
----

=== `@Walk` to recursively `Stream` all matches

What if your Maven project structure is fairly deep and has modules inside modules?  By default, returning a `Stream` or array will only the matches immediately under the current directory, in our case the `Project` directory.

If we want to do a recursive walk by adding the `@Walk` annotation.

[source,java]
----
import java.util.stream.Stream;
import org.tomitribe.util.paths.Filter;
import org.tomitribe.util.paths.Walk;

public interface Project {
    @Walk
    @Filter(HasPomXml.class)
    Stream<Module> modules();
}
----

=== `@Walk` with `maxDepth` to limit recursion depth

Under the covers `java.nio.file.Files.walk` is used to traverse, filter each matching file, and return it as a `Stream`.  If happen to know your modules are not more than say 2 or 3 directories deep, you can specify a `maxDepth` to speed up the walk.

[source,java]
----
import java.util.stream.Stream;
import org.tomitribe.util.paths.Filter;
import org.tomitribe.util.paths.Walk;

public interface Project {
    @Walk(maxDepth = 3)
    @Filter(HasPomXml.class)
    Stream<Module> modules();
}
----

=== `@Walk` with `minDepth` to skip shallow results

You can also specify a `minDepth` to skip results that are too close to the root.  For example, to exclude the root directory itself and only include paths that are at least 1 level deep:

[source,java]
----
public interface Work extends Dir {
    @Walk(minDepth = 1)
    Stream<Path> minOne();
}
----

The `minDepth` and `maxDepth` can be combined to window into a specific range of the tree:

[source,java]
----
public interface Work extends Dir {
    @Walk(minDepth = 2, maxDepth = 2)
    Stream<Path> exactlyTwoDeep();
}
----

== `@Mkdir`

To force a directory to be created simply annotate it with `@Mkdir` as follows.  When the `target()` method is invoked a check will be done and the directory created lazily if it needed.

[source,java]
----
public interface Project {
    Src src();

    @Mkdir
    Path target();

    @Name("pom.xml")
    Path pomXml();
}
----

== `@Mkdirs`

The above `@Mkdir` instruction will still fail if the path leading up to `target` does not exist.  It's possible to create all parent directories via `@Mkdirs`

[source,java]
----
public interface Project {
    Src src();
}
----

[source,java]
----
public interface Src  {
    Section main();
    Section test();
}
----

[source,java]
----
public interface Section {
    @Mkdirs
    Path java();

    @Mkdir
    Path resources();
}
----

In this example the path `src/main/java` would be created if we invoke code like this:

[source,java]
----
Project project = ...

final Path srcMainJava = project.src().main().java();
----

Here we could safely write files into the `srcMainJava` reference as the directory and any parents would have been automatically created the moment `java()` was called.

NOTE: The path `src/test/java` would still not exist unless `project.src().test().java()` is also called.

== `@Parent` for navigating up the tree

Sometimes when you're deep in a directory tree you want to navigate back up to a parent directory.  The `@Parent` annotation lets you do this.

[source,java]
----
public interface Module extends Dir {
    @Name("pom.xml")
    Path pomXml();

    Src src();
}

public interface Src {
    @Parent
    Module module();

    Section main();
    Section test();
}
----

With `@Parent` the `Src.module()` method navigates one level up -- the equivalent of `..` in a file path -- and returns a `Module` proxy for the parent directory.

By default `@Parent` goes up one level.  You can specify a depth to go further up:

[source,java]
----
public interface Section {
    @Parent(2)
    Module module();

    Java java();
    Path resources();
}

public interface Java extends Dir {
    @Parent(3)
    Module module();
}
----

Here `Section.module()` navigates 2 levels up (from `src/main` back to the project root) and `Java.module()` navigates 3 levels up (from `src/main/java` back to the project root).

== Extending the `Dir` interface

Interfaces can optionally extend `Dir` to gain several built-in convenience methods:

[source,java]
----
public interface Module extends Dir {
    @Name("pom.xml")
    Path pomXml();

    Src src();
}
----

The `Dir` interface provides:

 - `dir()` -- returns the `Path` for this directory
 - `get()` -- synonym for `dir()`
 - `dir(String name)` -- returns a `Dir` wrapping a named subdirectory
 - `file(String name)` -- returns the `Path` for a named file or subdirectory
 - `parent()` -- returns the parent `Path`
 - `mkdir()` -- creates this directory (fails if parent doesn't exist)
 - `mkdirs()` -- creates this directory and any missing parents
 - `delete()` -- recursively deletes this directory and all contents
 - `walk()` -- returns a `Stream<Path>` of all files and directories recursively
 - `walk(int depth)` -- same as `walk()` but limited to a given depth
 - `files()` -- returns a `Stream<Path>` of only files (no directories) recursively
 - `files(int depth)` -- same as `files()` but limited to a given depth

== Custom wrapper objects

Instead of returning `Path` or another interface, methods can return custom classes that wrap a `Path`.  The class must either have a public constructor taking a single `Path` argument or a public static factory method taking a single `Path` argument and returning the class type.

=== Constructor-based wrapper

[source,java]
----
public static class Pom {
    private final Path file;

    public Pom(final Path file) {
        this.file = file;
    }

    public Path getFile() {
        return file;
    }
}

public interface Module extends Dir {
    @Name("pom.xml")
    Pom pomXml();
}
----

=== Factory method-based wrapper

[source,java]
----
public static class Archivo {
    private final Path path;

    private Archivo(final Path path) {
        this.path = path;
    }

    public static Archivo from(final Path path) {
        return new Archivo(path);
    }
}

public interface Module extends Dir {
    @Walk
    @Filter(IsJava.class)
    Stream<Archivo> streamOfFiles();

    @Walk
    @Filter(IsJava.class)
    Archivo[] arrayOfFiles();
}
----

Custom wrappers work with all return types: single values, arrays, and streams.

== Default methods

Interfaces can include default methods for custom logic.  The proxy will delegate to the default implementation.

[source,java]
----
public interface Repository extends Dir {
    default Group group(final String name) {
        final String path = name.replace(".", "/");
        final Group group = Dir.of(Group.class, dir().resolve(path));
        group.mkdirs();
        return group;
    }
}

public interface Group extends Dir {
}
----

[source,java]
----
Repository repo = Dir.of(Repository.class, someDir);
Group group = repo.group("org.color");
----
